export const FETCH_ALL_USERS = "FETCH_ALL_USERS";
export const FETCH_ALL_USERS_SUCCESS = "FETCH_ALL_USERS_SUCCESS";
export const FETCH_ALL_USERS_ERROR = "FETCH_ALL_USERS_ERROR";

export const FETCH_DETAIL_USER = "FETCH_DETAIL_USER";
export const FETCH_DETAIL_USER_SUCCESS = "FETCH_DETAIL_USER_SUCCESS";
export const FETCH_DETAIL_USER_ERROR = "FETCH_DETAIL_USER_ERROR";

export const HANDLE_PHOTO_USER = "HANDLE_PHOTO_USER";
export const HANDLE_FIRSTNAME_USER= "HANDLE_FIRSTNAME_USER";
export const HANDLE_LASTNAME_USER = "HANDLE_LASTNAME_USER";
export const HANDLE_AGE_USER = "HANDLE_AGE_USER";
export const HANDLE_ID_USER = "HANDLE_ID_USER";